[tool.poetry]
name = "gh-repo-organizer"
version = "0.1.0"
description = "A tool to organize GitHub repositories."
authors = ["Albert Orlando <albertjorlando@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/albeorla/gh-repo-organizer"
packages = [{include = "repo_organizer", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
GitPython = "3.1.44"
langchain = "0.3.24"
langchain_anthropic = "0.3.12"
langchain_core = "0.3.56"
pydantic = "2.11.3"
python-dotenv = "1.1.0"
rich = "^13.0.0"
tenacity = "8.5.0"
tqdm = "4.67.1"
typer = {extras = ["all"], version = "^0.9.0"}
shellingham = "^1.5.4"

[tool.poetry.group.dev.dependencies]
ruff = ">=0.1.8"

[tool.poetry.scripts]
repo-analyzer = "repo_organizer.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88